<!DOCTYPE html>
<html lang="en"><head>
<script src="3-integer-programming_files/libs/clipboard/clipboard.min.js"></script>
<script src="3-integer-programming_files/libs/quarto-html/tabby.min.js"></script>
<script src="3-integer-programming_files/libs/quarto-html/popper.min.js"></script>
<script src="3-integer-programming_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="3-integer-programming_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="3-integer-programming_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="3-integer-programming_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="Alex L. Wang">
  <title>Integer programming</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="3-integer-programming_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="3-integer-programming_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="3-integer-programming_files/libs/revealjs/dist/theme/quarto-5ae9c59b2727fcd5357d4f034d95f9e0.css">
  <link rel="stylesheet" href="custom.css">
  <link href="3-integer-programming_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="3-integer-programming_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="3-integer-programming_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="3-integer-programming_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
<script src="mathjax-config.js"></script>
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Integer programming</h1>
  <p class="subtitle">MGMT 306</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Alex L. Wang 
</div>
        <p class="quarto-title-affiliation">
            Purdue University
          </p>
    </div>
</div>

</section>
<section>
<section id="what-is-an-integer-program" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>What is an integer program?</h1>

</section>
<section id="motivation-for-integer-programming" class="slide level2">
<h2>Motivation for Integer Programming</h2>
<ul>
<li>In a LP, the variables can be set to any real value <em>including fractional values</em></li>
<li>In an <span class="highlight">Integer Linear Program</span>, we are allowed to constrain variables to be
<ul>
<li><span class="highlight">integers</span>: …, -3, -2, -1, 0, 1, 2, 3, …</li>
<li><span class="highlight">binary</span>: 0 or 1</li>
</ul></li>
<li>Integer programs allow us to model variables that are naturally
<ul>
<li>integers, e.g., # of bikes to make</li>
<li>binary, e.g., should we accept a contract yes/no</li>
</ul></li>
</ul>
</section>
<section id="integer-linear-program" class="slide level2">
<h2>Integer Linear Program</h2>
<ul>
<li>An <span class="highlight">integer linear program (ILP)</span>, or <span class="highlight">integer program (IP)</span> for short, is a <strong>model</strong> (decision variables, objective function, constraints) where
<ul>
<li>Objective function is linear</li>
<li>Some variables are constrained to be integers or binary</li>
<li>Remaining constraints are standard form linear constraints</li>
</ul></li>
</ul>
</section>
<section id="what-does-an-integer-program-look-like" class="slide level2">
<h2>What does an integer program look like?</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><span class="math display">\[
\begin{aligned}
\max\quad&amp; 3x_{1} + 2x_{2}\\
\text{s.t.}\quad&amp; 3x_{1} + x_{2} \leq 9\\
&amp; x_{1} + 3x_{2} \leq 7\\
&amp; -x_{1} + x_{2} \leq 1\\
&amp; x_{1}, x_{2} \geq 0 \text{ and integer}\\
\end{aligned}
\]</span></p>
<ul>
<li>Things to notice:
<ul>
<li>Objective function is linear in variables</li>
<li>Some constraints of the form <span class="math inline">\(x_i\)</span> integer or <span class="math inline">\(x_i\)</span> binary</li>
<li>All other constraints are linear</li>
</ul></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="3-fig/slide-05.png" class="quarto-figure quarto-figure-center" alt="Feasible region of an Integer Program Problem with objective function line running through its optimal solution."></p>
</figure>
</div>
</div></div>
</section>
<section id="why-do-we-care-about-integer-programs" class="slide level2">
<h2>Why do we care about integer programs?</h2>
<ul>
<li>Compared to LPs, IPs have more modeling power (more accurate models), but are also more difficult to solve</li>
</ul>
</section></section>
<section>
<section id="lp-relaxations-of-ips" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>LP Relaxations of IPs</h1>

</section>
<section id="ips-have-lp-relaxations" class="slide level2">
<h2>IPs have LP relaxations</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>Given an IP, we can <span class="highlight">relax</span> (drop) the IP constraints to get an LP <span class="math display">\[
\begin{aligned}
\max\quad&amp; 3x_{1} + 2x_{2}\\
\text{s.t.}\quad&amp; 3x_{1} + x_{2} \leq 9\\
&amp; x_{1} + 3x_{2} \leq 7\\
&amp; -x_{1} + x_{2} \leq 1\\
&amp; x_{1}, x_{2} \geq 0 \text{ and integer}
\end{aligned}
\]</span></li>
</ul>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="3-fig/slide-08.png" class="quarto-figure quarto-figure-center" alt="Feasible region of an Integer Program Problem with objective function line running through its optimal solution."></p>
</figure>
</div>
</div></div>
</section>
<section id="ips-have-lp-relaxations-1" class="slide level2">
<h2>IPs have LP relaxations</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><span class="math display">\[
\begin{aligned}
\max\quad&amp; 3x_{1} + 2x_{2}\\
\text{s.t.}\quad&amp; 3x_{1} + x_{2} \leq 9\\
&amp; x_{1} + 3x_{2} \leq 7\\
&amp; -x_{1} + x_{2} \leq 1\\
&amp; x_{1}, x_{2} \geq 0
\end{aligned}
\]</span></p>
<ul>
<li>The optimal value of the LP relaxation will be better than the optimal value of the IP (larger for maximize, smaller for minimize)</li>
<li>Rounding the LP optimal solution is not guaranteed to find the ILP optimal solution</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="3-fig/slide-09.png" class="quarto-figure quarto-figure-center" alt="Feasible region of a Linear Program Problem with objective function line running through its optimal solution. The optimal value is better than that of the original IP problem."></p>
</figure>
</div>
</div></div>
</section></section>
<section>
<section id="capital-budgeting-example" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Capital budgeting example</h1>

</section>
<section id="problem-description" class="slide level2">
<h2>Problem Description</h2>
<ul>
<li>The local parks department would like to construct new rec facilities to encourage citizens to be healthier. It can build at most one of each facility type. They want to maximize expected daily use.</li>
<li>They have a budget of $800,000 and 13 acres of land.</li>
<li>We cannot build both the swimming pool and tennis center.</li>
<li>If a tennis center is built, then a gym must be built.</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Expected daily use</th>
<th style="text-align: left;">Cost ($)</th>
<th style="text-align: left;">Land req’d (acres)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Swimming pool</td>
<td style="text-align: left;">450</td>
<td style="text-align: left;">300,000</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tennis center</td>
<td style="text-align: left;">150</td>
<td style="text-align: left;">100,000</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Athletic field</td>
<td style="text-align: left;">500</td>
<td style="text-align: left;">250,000</td>
<td style="text-align: left;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gymnasium</td>
<td style="text-align: left;">550</td>
<td style="text-align: left;">400,000</td>
<td style="text-align: left;">3</td>
</tr>
</tbody>
</table>
</section>
<section id="ip-model-variables-and-objective-function" class="slide level2">
<h2>IP Model Variables and Objective Function</h2>
<ul>
<li>Variables <span class="math display">\[\begin{aligned}
  &amp;S &amp;&amp;\text{whether we build a swimming pool}\\
  &amp;T &amp;&amp;\text{whether we build a tennis center}\\
  &amp;A &amp;&amp;\text{whether we build an athletic field}\\
  &amp;G &amp;&amp;\text{whether we build a gymnasium}
\end{aligned}\]</span></li>
<li>Objective function <span class="math display">\[\max  \quad 450 S + 150 T + 500 A + 550 G \quad \text{(expected daily use)}\]</span></li>
</ul>
</section>
<section id="ip-model-constraints" class="slide level2">
<h2>IP Model Constraints</h2>
<ul>
<li><span class="math inline">\(S\)</span>, <span class="math inline">\(T\)</span>, <span class="math inline">\(A\)</span>, <span class="math inline">\(G\)</span> model yes/no decision so: <span class="math display">\[S, T, A, G \text{ are binary}\]</span></li>
<li>Budget of $800,000 and 13 acres of land: <span class="math display">\[\begin{aligned}
&amp;300 S + 100 T + 250 A + 400 G \leq 800 &amp;&amp;\text{(budget constraint in \$K)}\\
&amp;2 S + 3 T + 7 A + 3 G \leq 13  &amp;&amp;\text{(acreage constraint)}
\end{aligned}\]</span></li>
</ul>
</section>
<section id="ip-model-constraints-continued" class="slide level2">
<h2>IP Model Constraints (continued)</h2>
<ul>
<li>We cannot build both the swimming pool and tennis center <span class="math display">\[S + T \leq 1  \quad\text{(not both swimming pool and tennis center)}\]</span></li>
<li>If a tennis center is built, then a gym must be built <span class="math display">\[T – G \leq 0  \quad\text{(if tennis center, then gym)}\]</span></li>
</ul>
</section>
<section id="a-closer-look-at-logical-constraints" class="slide level2">
<h2>A closer look at logical constraints</h2>
<ul>
<li><strong>We cannot build both the swimming pool and tennis center</strong></li>
<li>This statement is either satisfied or violated depending on whether we built a pool and whether we build a tennis center</li>
<li>The <span class="math inline">\(S\)</span>, <span class="math inline">\(T\)</span> variables each have two possible values</li>
<li>We want to write a linear constraint on <span class="math inline">\(S\)</span> and <span class="math inline">\(T\)</span> that is true exactly when the statement is satisfied</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>S</th>
<th>T</th>
<th>Statement</th>
<th><span class="math inline">\(S+T\leq 1\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0</td>
<td>True</td>
<td>True</td>
</tr>
<tr class="even">
<td>0</td>
<td>1</td>
<td>True</td>
<td>True</td>
</tr>
<tr class="odd">
<td>1</td>
<td>0</td>
<td>True</td>
<td>True</td>
</tr>
<tr class="even">
<td>1</td>
<td>1</td>
<td>False</td>
<td>False</td>
</tr>
</tbody>
</table>
</section>
<section id="a-closer-look-at-logical-constraints-continued" class="slide level2">
<h2>A closer look at logical constraints (continued)</h2>
<ul>
<li><strong>If a tennis center is built, then a gym must be built</strong></li>
<li>This statement is either satisfied or violated depending on whether we built a pool and whether we build a tennis center</li>
<li>The <span class="math inline">\(T\)</span>, <span class="math inline">\(G\)</span> variables each have two possible values</li>
<li>We want to write a linear constraint on <span class="math inline">\(T\)</span> and <span class="math inline">\(G\)</span> that is true exactly when the statement is satisfied</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>T</th>
<th>G</th>
<th>Statement</th>
<th><span class="math inline">\(T - G \leq 0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>0</td>
<td>True</td>
<td>True</td>
</tr>
<tr class="even">
<td>0</td>
<td>1</td>
<td>True</td>
<td>True</td>
</tr>
<tr class="odd">
<td>1</td>
<td>0</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<td>1</td>
<td>1</td>
<td>True</td>
<td>True</td>
</tr>
</tbody>
</table>
</section>
<section id="integer-program-formulation" class="slide level2">
<h2>Integer Program formulation</h2>
<p><span class="math display">\[\begin{aligned}
    &amp;S &amp;&amp;\text{whether we build a swimming pool}\\
    &amp;T &amp;&amp;\text{whether we build a tennis court}\\
    &amp;A &amp;&amp;\text{whether we build an athletic field}\\
    &amp;G &amp;&amp;\text{whether we build a gymnasium}
\end{aligned}\]</span> <span class="math display">\[\begin{aligned}
\max\quad&amp;450 S + 150 T + 500 A + 550 G &amp;\text{(exp daily use)}\\
\text{s.t.}\quad&amp;300 S + 100 T + 250 A + 400 G \leq 800 &amp;\text{(budg. in \$K)}\\
&amp;2 S + 3 T + 7 A + 3 G \leq 13  &amp;\text{(acreage constraint)}\\
&amp;S + T \leq 1   &amp;\text{(not both S and T)}\\
&amp;T – G \leq 0   &amp;\text{(if T, then G)}\\
&amp;S, T, A, G \text{ are binary}
\end{aligned}\]</span></p>
</section>
<section id="spreadsheet-model" class="slide level2">
<h2>Spreadsheet Model</h2>
<ul>
<li>We will set up the Excel spreadsheet just like for a linear program</li>
</ul>

<img data-src="3-fig/slide-17.png" class="quarto-figure quarto-figure-center r-stretch" alt="Excel implementation of the capital budgeting problem."></section>
<section id="how-to-set-up-solver-for-integer-programs" class="slide level2">
<h2>How to set up Solver for Integer Programs</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>Similar to setting up Solver for LP except that you need to add integrality restrictions (“int” or “bin”) on integer variables as shown in the Solver Parameters Box.</li>
<li>We will use “Simplex LP” with additional options (next slide)</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="3-fig/slide-19.png" class="quarto-figure quarto-figure-center" alt="How to set up Solver for an ILP problem."></p>
</figure>
</div>
</div></div>
</section>
<section id="solver-options-for-integer-programs" class="slide level2">
<h2>Solver Options for Integer Programs</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>In the Solver Options dialogue box, set the Integer Optimality % to 0 as shown to the right.</li>
<li>With very large IP, this could cause a very long run time to find the optimal solution.</li>
<li>With the small IP, this will ensure that we get the optimal solution.</li>
</ul>
</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="3-fig/slide-20.png" class="quarto-figure quarto-figure-center" alt="Solver options for Simplex LP algorithm for ILP problems."></p>
</figure>
</div>
</div></div>
</section>
<section id="excel-usage" class="slide level2">
<h2>Excel usage</h2>
<ul>
<li>The optimal solution:</li>
</ul>

<img data-src="3-fig/slide-21.png" class="quarto-figure quarto-figure-center r-stretch" alt="Solved Excel spreadsheet with optimal solution for the Capital Budgeting example."></section></section>
<section>
<section id="fixed-cost-model" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Fixed cost model</h1>

</section>
<section id="problem-description-1" class="slide level2">
<h2>Problem Description</h2>
<ul>
<li>Franklin clothing company manufactures dresses, shorts and pants</li>
<li>They do not own their own equipment and must pay a fixed cost to produce each type of garment</li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Labor (hrs)</th>
<th>Cloth (sq. yd.)</th>
<th>Revenue ($)</th>
<th>Rental cost ($/week)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dresses</td>
<td>3</td>
<td>4</td>
<td>15</td>
<td>200</td>
</tr>
<tr class="even">
<td>Shorts</td>
<td>2</td>
<td>3</td>
<td>8</td>
<td>150</td>
</tr>
<tr class="odd">
<td>Pants</td>
<td>6</td>
<td>4</td>
<td>14</td>
<td>100</td>
</tr>
<tr class="even">
<td>Available</td>
<td>150/week</td>
<td>160/week</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="problem-description-continued" class="slide level2">
<h2>Problem Description (continued)</h2>
<ul>
<li>Additional requirements are:
<ul>
<li>If shorts machinery is rented, then at least 40 shorts should be produced per week</li>
<li>If pants machinery is rented, then at most 30 dresses should be produced per week</li>
</ul></li>
<li>Formulate an IP whose solution maximizes Franklin’s profit</li>
</ul>
</section>
<section id="ip-formulation-variables-and-objective" class="slide level2">
<h2>IP formulation Variables and Objective</h2>
<ul>
<li><p>Variables: <span class="math display">\[\begin{aligned}
&amp;D &amp;&amp;\text{number of dresses to produce/week}\\
&amp;S &amp;&amp;\text{number of shorts to produce/week}\\
&amp;P &amp;&amp;\text{number of pants to produce/week}\\
&amp;R_D &amp;&amp;\text{whether or not we rent dress machinery}\\
&amp;R_S &amp;&amp;\text{whether or not we rent shorts machinery}\\
&amp;R_P &amp;&amp;\text{whether or not we rent pants machinery}
\end{aligned}\]</span></p></li>
<li><p>Objective: <span class="math display">\[\max\qquad 15 D + 8 S + 14 P – 200 R_D – 150 R_S – 100 R_P\qquad\text{(total profit)}\]</span></p></li>
</ul>
</section>
<section id="ip-formulation-constraints" class="slide level2">
<h2>IP formulation constraints</h2>
<ul>
<li><p>Standard “allocation type” constraints <span class="math display">\[\begin{aligned}
&amp;3 D + 2 S + 6 P \leq 150   &amp;&amp;\text{(labor)}\\
&amp;4 D + 3 S + 4 P \leq 160   &amp;&amp;\text{(cloth)}\\
&amp;D, S, P \geq 0     &amp;&amp;\text{(nonnegativity)}
\end{aligned}\]</span></p></li>
<li><p>Binary/integer constraints <span class="math display">\[\begin{aligned}
&amp;D,S,P\text{ are integers}  &amp;&amp;\text{(Integer constraints)}\\
&amp;R_D,R_S,R_P\text{ are binary}  &amp;&amp;\text{(Binary constraints)}
\end{aligned}\]</span></p></li>
</ul>
</section>
<section id="linking-constraints-big-m-constraint" class="slide level2">
<h2>Linking constraints / Big-M constraint</h2>
<ul>
<li><strong>If we do not rent dress machinery, then we may not produce dresses</strong>
<ul>
<li>Suppose <span class="math inline">\(M\)</span> is a big number and consider the constraint <span class="math display">\[D \leq M\cdot R_D\]</span></li>
<li>If <span class="math inline">\(R_D=0\)</span>, the only way to satisfy this constraint is to set <span class="math inline">\(D=0\)</span></li>
<li>If <span class="math inline">\(R_D=1\)</span>, this introduces a new constraint <span class="math inline">\(D\leq M\)</span> This is fine as long as <span class="math inline">\(M\)</span> is large enough that <span class="math inline">\(D\leq M\)</span> doesn’t cut off the optimal solution.</li>
</ul></li>
<li>Need to ask: “What is the maximum number of dresses we can produce?”</li>
</ul>
</section>
<section id="how-to-choose-m" class="slide level2">
<h2>How to choose M</h2>
<ul>
<li>In this example, our standard constraints say: <span class="math display">\[\begin{aligned}
&amp;3 D + 2 S + 6 P \leq 150   &amp;&amp;\text{(labor)}\\
&amp;4 D + 3 S + 4 P \leq 160   &amp;&amp;\text{(cloth)}
\end{aligned}\]</span>
<ul>
<li>The labor constraint restricts <span class="math inline">\(D \leq 50\)</span></li>
<li>The cloth constraint restricts <span class="math inline">\(D \leq 40\)</span></li>
</ul></li>
<li>Hence, there is no feasible solution that produces more than 40 dresses.</li>
<li>So, we can use the linking constraint: <span class="math display">\[D – 40 R_D \leq 0\]</span></li>
</ul>
</section>
<section id="linking-constraints-practice" class="slide level2">
<h2>Linking constraints practice</h2>
<ul>
<li>With your neighbor, write the linking constraints for shorts and pants</li>
</ul>
</section>
<section id="ip-formulation-recap" class="slide level2">
<h2>IP Formulation Recap</h2>
<ul>
<li><p>Objective: <span class="math display">\[\max\qquad 15 D + 8 S + 14 P – 200 R_D – 150 R_S – 100 R_P\qquad\text{(total profit)}\]</span></p></li>
<li><p>Constraints <span class="math display">\[\begin{aligned}
&amp;3 D + 2 S + 6 P \leq 150   &amp;&amp;\text{(labor)}\\
&amp;4 D + 3 S + 4 P \leq 160   &amp;&amp;\text{(cloth)}\\
&amp;D – 40 R_D \leq 0      &amp;&amp;\text{(linking constraint dresses)}\\
&amp;S – 53.33 R_S \leq 0       &amp;&amp;\text{(linking constraint shorts)}\\
&amp; P – 25 R_P \leq 0     &amp;&amp;\text{(linking constraint paints)}\\
&amp;D,S,P\geq 0\text{ and integer}\\
&amp;R_D,R_S,R_P\text{ are binary}
\end{aligned}\]</span></p></li>
<li><p>Still missing: two logical constraints</p></li>
</ul>
</section>
<section id="logical-constraint-1" class="slide level2">
<h2>Logical constraint 1</h2>
<ul>
<li><p><strong>If the shorts machinery is rented, then at least 40 shorts should be produced per week.</strong> <span class="math display">\[S \geq 40 R_S\]</span></p>
<p><strong>Explanation</strong>. Renting shorts machinery (<span class="math inline">\(R_S = 1\)</span>) forces <span class="math inline">\(S\geq 40\)</span>. Not renting shorts machinery (<span class="math inline">\(R_S=0\)</span>) does not cut off the optimal solution.</p></li>
</ul>
</section>
<section id="logical-constraint-2" class="slide level2">
<h2>Logical constraint 2</h2>
<ul>
<li>__If pants machinery is rented, then at most 30 dresses should be produced per week.– <span class="math display">\[D \leq 40 – 10 R_P\]</span></li>
</ul>
<p><strong>Explanation</strong>. Renting pants machinery (<span class="math inline">\(R_P=1\)</span>) forces <span class="math inline">\(D\leq 30\)</span>. Not renting pants machinery introduces the constraint <span class="math inline">\(D\leq 40\)</span>, which does not cut off the optimal solution.</p>
</section>
<section id="spreadsheet-model-1" class="slide level2">
<h2>Spreadsheet model</h2>

<img data-src="3-fig/slide-35.png" class="quarto-figure quarto-figure-center r-stretch" alt="Completed spreadsheet model of the Franklin Clothing Company problem"></section></section>
<section>
<section id="vehicle-routing-model" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Vehicle routing model</h1>
<p>Example of a covering problem</p>
</section>
<section id="truckco-problem" class="slide level2">
<h2>TruckCo problem</h2>
<ul>
<li>TruckCo wants to choose truck routes to serve 5 cities: A, B, C, D, E</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Route no.</th>
<th>Route</th>
<th>Cost</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>A-C-D</td>
<td>10</td>
</tr>
<tr class="even">
<td>2</td>
<td>A-D-E</td>
<td>12</td>
</tr>
<tr class="odd">
<td>3</td>
<td>A-B-E</td>
<td>12</td>
</tr>
<tr class="even">
<td>4</td>
<td>B-C-E</td>
<td>13</td>
</tr>
<tr class="odd">
<td>5</td>
<td>B-D-E</td>
<td>11</td>
</tr>
<tr class="even">
<td>6</td>
<td>C-D-E</td>
<td>9</td>
</tr>
<tr class="odd">
<td>7</td>
<td>A-B</td>
<td>7</td>
</tr>
<tr class="even">
<td>8</td>
<td>B-C</td>
<td>8</td>
</tr>
<tr class="odd">
<td>9</td>
<td>D-E</td>
<td>8</td>
</tr>
</tbody>
</table>
<ul>
<li>Write an ILP to cover all cities with minimum cost.</li>
</ul>
</section>
<section id="truckco-problem-1" class="slide level2">
<h2>TruckCo problem</h2>
<ul>
<li>Decision Variables: xi represents whether or not we choose route i for i = 1,…,9</li>
<li>Objective function: Minimize 10 x1 + 12 x2 + 12 x3 + … + 8 x9 (total cost)</li>
<li>Constraints: x1 + x2 + x3 + x7 ≥ 1 (service to city A) … x2 + x3 + x4 + x5 + x6 + x9 ≥ 1 (service to city E) xi is binary for i = 1, …, 9</li>
</ul>
</section>
<section id="truckco-spreadsheet" class="slide level2">
<h2>TruckCo spreadsheet</h2>

<img data-src="3-fig/slide-39.png" class="quarto-figure quarto-figure-center r-stretch" alt="TruckCo spreadsheet"></section>
<section id="truckco-spreadsheet-1" class="slide level2">
<h2>TruckCo spreadsheet</h2>
<ul>
<li>Don’t forget to set the binary constraints and to turn the integer optimality to 0%</li>
</ul>

<img data-src="3-fig/slide-40.png" class="quarto-figure quarto-figure-center r-stretch" alt="TruckCo spreadsheet"></section>
<section id="truckco-spreadsheet-with-solution" class="slide level2">
<h2>TruckCo spreadsheet with solution</h2>

<img data-src="3-fig/slide-41.png" class="quarto-figure quarto-figure-center r-stretch" alt="TruckCo spreadsheet with solution"></section></section>
<section>
<section id="modeling-logical-conditions" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Modeling logical conditions</h1>

</section>
<section id="what-are-logical-conditions" class="slide level2">
<h2>What are logical conditions</h2>
<ul>
<li>A logical statement is a “sentence” that can be either true or false, but not both. There should be no ambiguity.
<ul>
<li>Example
<ul>
<li>The local parks department built a tennis center.</li>
</ul></li>
</ul></li>
<li>A question is not a logical statement. A question is not true or false.</li>
<li>A logical constraint requires a logical statement made about some variables to be true.</li>
<li>Once the variables are fixed, the logical constraint either holds or it does not hold.</li>
</ul>
</section>
<section id="logical-conditions-cannot-be-placed-directly-into-ips" class="slide level2">
<h2>Logical conditions cannot be placed directly into IPs</h2>
<ul>
<li>Let’s go back to the parks example:</li>
<li>There was a constraint that we cannot build both the swimming pool and the tennis court Logical constraint: Not both S and T</li>
<li>For any assignment of 0 or 1 to S and 0 or 1 to T, this logical statement is either true or false</li>
</ul>
<div class="line-block">S | T | Not both S and T |</div>
<div class="line-block">— | — | — |</div>
<div class="line-block">0 | 0 | True |</div>
<div class="line-block">0 | 1 | True |</div>
<div class="line-block">1 | 0 | True |</div>
<div class="line-block">1 | 1 | False |</div>
</section>
<section id="logical-conditions-cannot-be-placed-directly-into-ips-1" class="slide level2">
<h2>Logical conditions cannot be placed directly into IPs</h2>
<ul>
<li>We cannot directly put the constraint Not both S and T into an Integer Program because this is not a linear constraint in standard linear form</li>
<li>So, we need to write a linear constraint (and put into standard linear form) that models this logical constraint</li>
<li>For example, S + T ≤ 1, correctly models this constraint</li>
<li>The following slides give you some building blocks and ways to put them together to model more interesting logical conditions</li>
</ul>
</section>
<section id="basic-logical-statements" class="slide level2">
<h2>Basic logical statements</h2>
<ul>
<li>We can build a logical statement from another logical statement</li>
<li>A represents “It is raining”</li>
<li>B represents “I am carrying an umbrella”</li>
</ul>
<div class="line-block">A | Not A |</div>
<div class="line-block">— | — |</div>
<div class="line-block">False | True |</div>
<div class="line-block">True | False |</div>
<div class="line-block">A | B | A and B |</div>
<div class="line-block">— | — | — |</div>
<div class="line-block">False | False | False |</div>
<div class="line-block">False | True | False |</div>
<div class="line-block">True | False | False |</div>
<div class="line-block">True | True | True |</div>
</section>
<section id="basic-logical-statements-1" class="slide level2">
<h2>Basic logical statements</h2>
<ul>
<li>Suppose A represents whether A is true or false B represents whether B is true or false</li>
<li>The logical constraint “A is true” can be modeled as A = 1</li>
<li>The logical constraint “A is false” can be modeled as A = 0</li>
<li>The logical constraint “A and B are both true” can be modeled as A + B = 2 (alternatively, A = 1 and B = 1)</li>
</ul>
</section>
<section id="basic-logical-statements-2" class="slide level2">
<h2>Basic logical statements</h2>
<ul>
<li>“A or B” is ambiguous in the English language. Depending on the situation, it means “at least one of A, B” or “exactly one of A, B”</li>
<li>In logic, we make this unambiguous by differentiating “or” form “exclusive or”</li>
</ul>
<div class="line-block">A | B | A or B |</div>
<div class="line-block">— | — | — |</div>
<div class="line-block">False | False | False |</div>
<div class="line-block">False | True | True |</div>
<div class="line-block">True | False | True |</div>
<div class="line-block">True | True | True |</div>
<div class="line-block">A | B | A xor B |</div>
<div class="line-block">— | — | — |</div>
<div class="line-block">False | False | False |</div>
<div class="line-block">False | True | True |</div>
<div class="line-block">True | False | True |</div>
<div class="line-block">True | True | False |</div>
</section>
<section id="basic-logical-statements-3" class="slide level2">
<h2>Basic logical statements</h2>
<ul>
<li>Suppose A represents whether A is true or false B represents whether B is true or false</li>
<li>The logical constraint “A or B” can be modeled as A + B ≥ 1</li>
<li>The logical constraint “A xor B” can be modeled as (exclusive or) A + B = 1</li>
</ul>
</section>
<section id="basic-logical-statements-4" class="slide level2">
<h2>Basic logical statements</h2>
<ul>
<li>“If …, then …” statements</li>
<li>Think: A = “You study for this quiz”, B = “You pass this quiz”</li>
<li>Think of “If A, then B” as a promise. If A is false, then nothing was promised, so the promise “If A, then B” is not broken regardless of B.</li>
<li>“If A, then B” can be modeled as x ≤ y</li>
</ul>
<div class="line-block">A | B | If A, then B |</div>
<div class="line-block">— | — | — |</div>
<div class="line-block">False | False | True |</div>
<div class="line-block">False | True | True |</div>
<div class="line-block">True | False | False |</div>
<div class="line-block">True | True | True |</div>
</section>
<section id="building-more-complicated-expressions" class="slide level2">
<h2>Building more complicated expressions</h2>
<ul>
<li>Statement: If (A or B), then C</li>
<li>This statement is equivalent to two separate statements: (If A, then C) and (If B, then C)</li>
<li>We can model the statement as the pair of constraints: A ≤ C B ≤ C</li>
<li>Or, the single constraint A + B ≤ 2C</li>
<li>BEWARE: You cannot just add two constraints together and expect that the new constraint models the original logical condition.</li>
</ul>
</section>
<section id="building-more-complicated-expressions-1" class="slide level2">
<h2>Building more complicated expressions</h2>
<ul>
<li>Statement: If A, then (B and C)</li>
<li>This statement is equivalent to two separate statements: (If A, then B) and (If A, then C)</li>
<li>We can model this statement as: A ≤ B A ≤ C</li>
<li>Or, as the single constraint 2A ≤ B + C</li>
<li>BEWARE: You cannot just add two constraints together and expect that the new constraint models the original logical condition.</li>
</ul>
</section>
<section id="building-more-complicated-expressions-2" class="slide level2">
<h2>Building more complicated expressions</h2>
<ul>
<li>Statement: If (A and B), then C</li>
<li>We can model the statement as the constraint: A + B ≤ 1 + C</li>
</ul>
</section>
<section id="building-more-complicated-expressions-3" class="slide level2">
<h2>Building more complicated expressions</h2>
<ul>
<li>Statement: If A, then (B or C)</li>
<li>We can model the statement as the pair of constraints: A ≤ B + C</li>
</ul>
</section>
<section id="general-rules" class="slide level2">
<h2>General rules</h2>
<ul>
<li>Rules:
<ul>
<li>If the statement uses (not A) then, we simply need to replace A with (1-A) and simplify.</li>
</ul></li>
</ul>
<div class="line-block">Logical statement | Linear constraints model the logical constraint | Alternate (caution) |</div>
<div class="line-block">— | — | — |</div>
<div class="line-block">A or B | A + B ≥ 1 | |</div>
<div class="line-block">If A, then B | A - B ≤ 0 | |</div>
<div class="line-block">A if and only if B | A - B = 0 | |</div>
<div class="line-block">If A or B, then C | A – C ≤ 0 and B – C ≤ 0 | A + B – 2C ≤ 0 |</div>
<div class="line-block">If A, then B and C | A – B ≤ 0 and A – C ≤ 0 | 2A – B – C ≤ 0 |</div>
<div class="line-block">If A and B, then C | A + B – C ≤&nbsp;1 | |</div>
<div class="line-block">If A, then B or C | A – B – C ≤ 0 | |</div>
</section>
<section id="practice" class="slide level2">
<h2>Practice</h2>
<ul>
<li>Continuing from the TruckCo problem</li>
<li>Write linear constraints modeling the logical constraints:
<ul>
<li>If route 1 is picked , then we may not pick route 2</li>
<li>If route 1 is picked or route 2 is not picked, then route 3 is picked</li>
<li>If route 1 is picked and route 2 is picked, then route 3 is picked and route 4 is not picked</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="assignment-model" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Assignment model</h1>

</section>
<section id="do-it-all-tailoring" class="slide level2">
<h2>Do-it-all tailoring</h2>
<ul>
<li>Do-it-All Tailoring has four tailors and four garments to make. The estimated time (in hours) it would take each tailor to make each garment is listed below. We are determining the optimal assignment of tailors to garments so that the total working time is minimized.</li>
<li>Assignment means: each garment must be worked on by exactly one tailor, each tailor must work on at most one garment.</li>
</ul>
<div class="line-block">&nbsp;| Tailor 1 | Tailor 2 | Tailor 3 | Tailor 4 |</div>
<div class="line-block">— | — | — | — | — |</div>
<div class="line-block">1. Wedding gown | 19 | 15 | 20 | 21 |</div>
<div class="line-block">2. Clown costume | 11 | 14 | 16 | 12 |</div>
<div class="line-block">3. Admiral’s uniform | 12 | 8 | 11 | 13 |</div>
<div class="line-block">4. Bullfighter outfit | 15 | 20 | 17 | 18 |</div>
</section>
<section id="do-it-all-tailoring-graph-representation" class="slide level2">
<h2>Do-it-all tailoring: graph representation</h2>
<ul>
<li>Graph (nodes and edges) representation:</li>
<li>Left: garments</li>
<li>Right: tailors</li>
<li>An assignment is a selection of edges so that every node on the left sees exactly one selected edge and every node on the right sees at most one selected edge</li>
</ul>

<img data-src="3-fig/slide-59.png" class="quarto-figure quarto-figure-center r-stretch" alt="Do-it-all tailoring: graph representation"></section>
<section id="do-it-all-tailoring-graph-representation-1" class="slide level2">
<h2>Do-it-all tailoring: graph representation</h2>
<ul>
<li>Graph (nodes and edges) representation:</li>
<li>Left: garments</li>
<li>Right: tailors</li>
<li>An assignment is a selection of edges so that every node on the left sees exactly one selected edge and every node on the right sees at most one selected edge</li>
</ul>

<img data-src="3-fig/slide-60.png" class="quarto-figure quarto-figure-center r-stretch" alt="Do-it-all tailoring: graph representation"></section>
<section id="do-it-all-tailoring-ip-formulation" class="slide level2">
<h2>Do-it-all tailoring: IP Formulation</h2>
<ul>
<li>Decision variables: 16 variables xij represents whether or not garment i is assigned to tailor j for i = 1,2,3,4 and j = 1,2,3,4</li>
<li>Objective function Min 19 x11 + 15 x12 + 20 x13 + … + 18 x44 (total time)</li>
</ul>
</section></section>
<section id="do-it-all-tailoring-ip-formulation-1" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Do-it-all tailoring: IP Formulation</h1>

</section>

<section id="do-it-all-tailoring-ip-formulation-2" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Do-it-all tailoring: IP Formulation</h1>

</section>

<section id="do-it-all-tailoring-completed-ip-formulation" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Do-it all tailoring: Completed IP Formulation</h1>

</section>

<section id="excel-usage-1" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Excel usage</h1>

</section>

<section>
<section id="excel-usage-2" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Excel usage</h1>

</section>
<section id="excel-usage-3" class="slide level2">
<h2>Excel usage</h2>

<img data-src="3-fig/slide-67.png" class="quarto-figure quarto-figure-center r-stretch" alt="Excel usage"></section></section>
<section>
<section id="excel-usage-4" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Excel usage</h1>

</section>
<section id="do-it-all-tailoring-modification" class="slide level2">
<h2>Do-it all tailoring: modification</h2>
<ul>
<li>How would we change the model if Tailor 2 cannot make the wedding gown (Job 1)?</li>
<li>Two ways:
<ul>
<li>We could add a constraint: x12 = 0,</li>
<li>We could set the time cost of x12 so high that the optimal solution is forced to set x12 = 0</li>
</ul></li>
<li>The first way is the simplest in terms of writing down the IP model. The second way is the simplest in terms of implementing in Excel.</li>
</ul>
</section>
<section id="practice-problem" class="slide level2">
<h2>Practice problem</h2>
<ul>
<li>This practice problem combines ideas from “assignment problems” and “fixed cost problems”</li>
</ul>
</section>
<section id="practice-problem-1" class="slide level2">
<h2>Practice problem</h2>
<ul>
<li>Jackie and Casey are planning a very large wedding and need to decide on caterers and meals. Including themselves, there will be 50 vegetarian guests, 20 gluten-sensitive guests, and 75 lactose intolerant guests.</li>
<li>There are three catering companies: (1) Star, (2) Big Blue, and (3) Unique Creations.</li>
<li>Each caterer charges a flat fee just to show up plus a price per guest depending on the different menus. Each caterer has a maximum number of guests they can serve.</li>
<li>Formulate an Integer Program to decide which caterers to hire (possibly multiple) and how many of each dish to order from each caterer to feed all their guests and to minimize costs.</li>
</ul>
<div class="line-block">Price per guest | Vegetarian | (2) Gluten-free | (3) Dairy-free |</div>
<div class="line-block">— | — | — | — |</div>
<div class="line-block">Star | 55 | 55 | 60 |</div>
<div class="line-block">Big Blue | 60 | 40 | 50 |</div>
<div class="line-block">Unique Creations | 120 | 40 | 30 |</div>
<div class="line-block">&nbsp;| Flat Fee | Capacity |</div>
<div class="line-block">— | — | — |</div>
<div class="line-block">Star | 250 | 120 |</div>
<div class="line-block">Big Blue | 200 | 125 |</div>
<div class="line-block">Unique Creations | 150 | 65 |</div>
</section>
<section id="practice-problem-2" class="slide level2">
<h2>Practice Problem</h2>
<ul>
<li>Decision Variables: xi represents whether or not to hire caterer i for i = 1,…, 3 yij represents how many of menu j to order from caterer i for i = 1,…,3 and j = 1,…,3</li>
<li>Objective: Minimize 250 x1 + 200 x2 + 150 x3 + 55 y11 + 55 y12 + … + 30 y33</li>
<li>(total cost)</li>
</ul>
</section>
<section id="practice-problem-3" class="slide level2">
<h2>Practice Problem</h2>
<ul>
<li>Constraints (hiring is binary) xi is binary for i = 1,…,3</li>
</ul>
<p>(number of meals is nonnegative and integer) yij ≥ 0 and integer for i = 1,…,3 and j = 1,…,3</p>
<p>(linking and capacity) y11 + y12 + y13 - 120 x1 ≤ 0 y21 + y22 + y23 - 125 x1 ≤ 0 y31 + y32 + y33 - 65 x1 ≤ 0</p>
<p>(need to feed all guests) y11 + y21 + y31 = 50 y12 + y22 + y23 = 20 y13 + y23 + y33 = 75</p>
</section></section>
<section id="practice-problem-4" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Practice problem</h1>

</section>

<section id="practice-problem-5" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Practice problem</h1>

</section>

<section id="practice-problem-6" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Practice problem</h1>

</section>

<section id="practice-problem-7" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Practice problem</h1>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="3-integer-programming_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="3-integer-programming_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="3-integer-programming_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="3-integer-programming_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="3-integer-programming_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="3-integer-programming_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="3-integer-programming_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="3-integer-programming_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="3-integer-programming_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="3-integer-programming_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@4/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>